[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
beastie = "8Gg4bD4regjmpvz2thxNkyjvPiyxUKTcLuLZpFh4XJpU"
grid = "EExeRoQMrfcJP28XQVjcE6khh3U8GC2RVZs28RNut5Br"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
