[workspace]
members = [ "modules/beastie_common", "modules/metalock", "programs/*" ]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
